musicplayer
Rancho2002/C-projects pull request #37
Opened 2022-10-22 15:03 UTC by rubykar

2022-10-22 16:01 UTC, Rancho2002 requested changes
pls add a readme file containing either a video demo, or screenshots explaining your code, @rubykar.

2022-10-23 03:28 UTC, Rancho2002 commented
hi @rubykar do this as soon as possible to gain your points in hacksquad.

2022-10-23 04:17 UTC, rubykar commented
I have added a readme file please check it out.

Thank you

2022-10-23 04:21 UTC, Rancho2002 commented
hi @rubykar it says like this when i run this code
![image](https://user-images.githubusercontent.com/92109154/197373483-f836dc29-77bc-40d7-b92f-429fa94c1bc7.png)
Pls give all necessary files, and the best if you provide a <b>video demo,/b> running your own code(no need to explain, just showing others how one should run this program). If you want any kind of help regarding adding video in readme, you can reach out to me.

2022-10-23 04:25 UTC, rubykar commented
Yeah sure on it

2022-10-23 04:51 UTC, rubykar commented on Musicplayer/README.md
> +
``

https://user-images.githubusercontent.com/49357847/197374401-b69f7fee-5c43-4669-ba7c-815071303327.mp4

2022-10-23 05:41 UTC, Rancho2002 approved these changes
Congrats @rubykar on making a successful PR 🥳🥳. You can contribute more and make this repo full of awesome C projects. Thank you 😊.

2022-10-23 05:41 UTC, merged